force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReviewTriggerHelper.cls
public class ReviewTriggerHelper {
    
    public static void afterUndeleteTriggerMethod(List<Review__c> reviews) {
        List<Review__c> anonymousReviews = [SELECT Id FROM Review__c WHERE Id IN :reviews];
        List<Contact> anonymousContacts = new List<Contact>([SELECT Id FROM Contact WHERE Name = 'ANONYMOUS REVIEWER' LIMIT 1]);
        
        for(Review__c review : anonymousReviews) {
            review.Reviewer__c = anonymousContacts[0].Id;
        }
        
        update anonymousReviews;

    }

}