force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Status_of_Negotiation__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Negotiation__c</fullName>
    <label>Status of Negotiation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Legal Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataFactory4TestCustomContractDeletion.cls
// UTILITY CLASS
@isTest
public class DataFactory4TestCustomContractDeletion {
    
    
    // ---- Status_of_Negotiation__c values: 
    // 		Approved, 
    // 		Archived, 
    // 		Denied, 
    // 		Legal Review, 
    // 		Pending, 
    // 		Rejected
  
 
    public static List<Contract__c> createTestContracts(Integer numRecs, String statusVal) {
        
        List<Contract__c> conts = new List<Contract__c>();
        
        for(Integer i=0;i<numRecs;i++) {
            Contract__c a = new Contract__c();
            a.Name='TestContract__c' + i;
            a.Status_of_Negotiation__c=statusVal;
 
            conts.add(a);
        }
        insert conts;
        return conts;
    }
    
    

    
}