force-app/main/default/objects/Product2/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <label>ISBN</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Product2Controller.cls
global without sharing class Product2Controller {
    public Product2Controller() {

    }

    @AuraEnabled(cacheable=true)
    global static Product2 getBookById(String bookId){
        Product2 book = [ SELECT Id, Name, Author__c, Genre__c, Year__c, ISBN__c, Description, 
        (SELECT UnitPrice FROM PricebookEntries)
        FROM Product2 WHERE Id = :bookId LIMIT 1 ];
        return book;
    }

    @AuraEnabled(cacheable=true)
    global static List<Product2> getBooksByAuthor(String authorName){
        List<Product2> books = [ SELECT Id, Name, Author__c, Genre__c, Year__c, ISBN__c, Description, 
        (SELECT UnitPrice FROM PricebookEntries)
        FROM Product2 WHERE Author__c = :authorName ];

        return books;
    }

    @AuraEnabled(cacheable=true)
    global static Account getBookAuthor(String authorName){
        Account author = [ SELECT Id, Description FROM Account WHERE Name = :authorName LIMIT 1 ];
        return author;
    }
}