force-app/main/default/objects/Product2/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <label>ISBN</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <label>Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

volcano dragon/force-app/main/default/objects/Review__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ProductTriggerHelperTest.cls
/**
 * Tests of the ProductTriggerHelper class.
 * @author Alonso del Arte
 */
@isTest
public class ProductTriggerHelperTest {
    
    /**
     * Test to make sure bad check digits for ISBN are rejected. For example, the
     * correct ISBN-13 for <i>Java in a Nutshell</i> is 978-1-49203-725-5, so 
     * 978-1-49203-725-6 should be rejected.
     */
     
     
    @isTest
    public static void testEnsureBadCheckDigitIsRejected() {
        Product2 book = new Product2(name = 'Java in a Nutshell', 
                                     author__c = 'David Flannagan and Ben Evans', 
                                     genre__c = 'Other', ISBN__c = 9781492037256L, 
                                     year__c = Date.today());
        Database.SaveResult result = Database.insert(book, false);
        System.assert(!result.isSuccess());
    }
    
    /**
     * Test to make sure a valid ISBN with the correct check digit is accepted. 
     * For example, the correct ISBN-13 for <i>Java in a Nutshell</i> is 
     * 978-1-49203-725-5.
     */
     
    @isTest
    public static void testEnsureCheckDigitChecksOut() {
        Product2 book = new Product2(name = 'Java in a Nutshell', 
                                     author__c = 'David Flannagan and Ben Evans', 
                                     genre__c = 'Other', ISBN__c = 9781492037255L, 
                                     year__c = Date.today());
        Database.SaveResult result = Database.insert(book, false);
        System.assert(result.isSuccess());
    }
    
    // TODO: Replace this test with a test that is correct and necessary.
    //       I have not seen this test fail, so I know it's either incorrect
    //  
    //     or unnecessary.
    @isTest
    public static void testCleanUpOrphanedReviews() {
        long isbn = 9785550321772379L;
        Product2 book = new Product2(name = 'Hemlock', 
                                     author__c = 'Bernardo Gerhardt', 
                                     genre__c = 'Other', ISBN__c = isbn, 
                                     year__c = Date.today());
        insert book;
        String reviewText = 'This book needs to be pulled for a rewrite.';
        Review__c review = new Review__c(book__c = book.Id, 
                                         content__c = reviewText);
        insert review;
        delete book;
        List<Review__c> reviews = [SELECT Id, Name, Content__c 
                                   FROM Review__c 
                                   WHERE Book__r.ISBN__c = :isbn];
        System.assertEquals(0, reviews.size());
    }

}