force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Line__c/Inventory_Line__c.object-meta.xml
<CustomObject>
    <label>Inventory Line</label>
    <nameField>
        <label>Inventory Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Line__c/fields/CapacityCompare__c.field-meta.xml
<CustomField>
    <fullName>CapacityCompare__c</fullName>
    <description>Returns True if current quantity of Inventory Line falls below 20% of Store&apos;s Inventory Quantity of the Capacity</description>
    <formula>If ( (20/100) &gt;= (Quantity__c / Inventory__r.Quantity__c) , &apos;true&apos;, &apos;false&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CapacityCompare</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Line__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Inventory Lines</relationshipLabel>
    <relationshipName>Inventory_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReplenishInventoryTriggerHelper.cls
public class ReplenishInventoryTriggerHelper {
    
    public static void handleTrigger(List<Inventory__c> inventoryList){      
        // Grabs all the inventory item products that are falling below or equal to 20% of the store's capacity
        List<Inventory_Line__c> inventory_line = [select id, inventory__r.store__r.contact__r.id FROM Inventory_Line__c WHERE CapacityCompare__c = 'true'];        
        Set<Id> contactIds = new Set<Id>();
		for (Inventory_Line__c iLc : inventory_line) {
                contactIds.add(iLc.inventory__r.store__r.contact__r.id);
        }        
        List<Contact> contactList = [SELECT id,FirstName,Email FROM Contact WHERE id IN :contactIds];
        sendEmails(contactList);
        
}
    public static void sendEmails(List<Contact> ContactsList){
        List<String> sendTo = new List<String>();
        // all email in the list
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();    
        for (Contact c : ContactsList){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject('Replenish Inventory Stock'); //Subject of the mail and the body of the mail
            mail.setHtmlBody('Hello ' + c.FirstName + ',' + '\n' + 'Please replenish your inventory to meet your customer needs. ' + 'For more details you can visit' + ' https://volcanodragon-pub/homepage');       
            mails.add(mail);             
        }
        // Step 5: Send all emails in the master list
        Messaging.sendEmail(mails);
    }

}