force-app/main/default/objects/Printing_Press__c/Printing_Press__c.object-meta.xml
<CustomObject>
    <label>Printing Press</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Printing Presses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

volcano dragon/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Printing_Press__c.field-meta.xml
<CustomField>
    <fullName>Printing_Press__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Printing Press</label>
    <referenceTo>Printing_Press__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of books to ship.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

volcano dragon/force-app/main/default/objects/Shipment__c/fields/Shipping_Cost__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Cost__c</fullName>
    <label>Shipping Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

volcano dragon/force-app/main/default/objects/Shipment__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Store to ship to.</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

volcano dragon/force-app/main/default/classes/shipmentTriggerTest.cls
@isTest
public class shipmentTriggerTest {
@testSetup
public static void createStoreAndPress() {

}

@isTest 
public static void calculateShippingWhenInsertAndPressIsSet() {
    Test.startTest();
    //48.46804666769003 mi between 10.00 and 10.50
    Store__c s = new Store__c(Name = 'test store', Location__Latitude__s = 10.00, Location__Longitude__s = 10.00) ;
    Printing_Press__c pp = new Printing_Press__c(Name='test press', Location__Latitude__s = 10.50, Location__Longitude__s = 10.50);
    insert s;
    insert pp;
    Shipment__c sh = new Shipment__c(Name='test shipment', Quantity__c=1, 
        Store__c = [SELECT Id FROM Store__c WHERE Name = 'test store' LIMIT 1].Id, 
        Printing_Press__c = [SELECT Id FROM Printing_Press__c WHERE Name = 'test press' LIMIT 1].Id);
    insert sh;
    sh = [SELECT Id, Shipping_Cost__c FROM Shipment__c WHERE Name = 'test shipment' LIMIT 1];
    Decimal estimated_cost = 48.46804666769003*2.34 + 10;
    Decimal actual_cost = sh.Shipping_Cost__c;
    System.assert(estimated_cost == actual_cost);
    Test.stopTest();

}

@isTest
public static void addPressAndCalculate() {
    Test.startTest();
    //48.46804666769003 mi between 10.00 and 10.50
    Store__c s = new Store__c(Name = 'test store', Location__Latitude__s = 10.00, Location__Longitude__s = 10.00) ;
    Printing_Press__c pp = new Printing_Press__c(Name='test press', Location__Latitude__s = 10.50, Location__Longitude__s = 10.50);
    insert s;
    insert pp;
    Shipment__c sh = new Shipment__c(Name='test shipment', Quantity__c=1, 
        Store__c = [SELECT Id FROM Store__c WHERE Name = 'test store' LIMIT 1].Id 
        //Printing_Press__c = [SELECT Id FROM Printing_Press__c WHERE Name = 'test press' LIMIT 1].Id);
    );
    insert sh;
    sh = [SELECT Id, Shipping_Cost__c FROM Shipment__c WHERE Name = 'test shipment' LIMIT 1];
    Decimal estimated_cost = 48.46804666769003*2.34 + 10;
    Decimal actual_cost = sh.Shipping_Cost__c;
    System.assert(estimated_cost == actual_cost);
    Test.stopTest();


}

@isTest
public static void addPressFindClosestAndCalculate() {
    Test.startTest();
    //48.46804666769003 mi between 10.00 and 10.50 according to Location.getDistance(loc1,loc2,'mi')
    Store__c s = new Store__c(Name = 'test store', Location__Latitude__s = 10.00, Location__Longitude__s = 10.00) ;
    Printing_Press__c pp = new Printing_Press__c(Name='test press', Location__Latitude__s = 10.50, Location__Longitude__s = 10.50);
    Printing_Press__c zz = new Printing_Press__c(Name='test press', Location__Latitude__s = 11.00, Location__Longitude__s = 11.00);
    insert s;
    insert pp;
    Shipment__c sh = new Shipment__c(Name='test shipment', Quantity__c=1, 
        Store__c = [SELECT Id FROM Store__c WHERE Name = 'test store' LIMIT 1].Id 
        //Printing_Press__c = [SELECT Id FROM Printing_Press__c WHERE Name = 'test press' LIMIT 1].Id);
    );
    insert sh;
    sh = [SELECT Id, Shipping_Cost__c FROM Shipment__c WHERE Name = 'test shipment' LIMIT 1];
    Decimal estimated_cost = 48.46804666769003*2.34 + 10;
    Decimal actual_cost = sh.Shipping_Cost__c;
    System.assert(estimated_cost == actual_cost);
    Test.stopTest();


}

@isTest
public static void addAThousandOrders() {
    Test.startTest();
    //48.46804666769003 mi between 10.00 and 10.50 according to Location.getDistance(loc1,loc2,'mi')
    Store__c s = new Store__c(Name = 'test store', Location__Latitude__s = 10.00, Location__Longitude__s = 10.00) ;
    Printing_Press__c pp = new Printing_Press__c(Name='test press', Location__Latitude__s = 10.50, Location__Longitude__s = 10.50);
    Printing_Press__c zz = new Printing_Press__c(Name='test press', Location__Latitude__s = 11.00, Location__Longitude__s = 11.00);
    insert s;
    insert pp;
    List<Shipment__c> shs = new List<Shipment__c>();
    s = [SELECT Id FROM Store__c WHERE Name = 'test store' LIMIT 1];
    for(Integer i = 0; i<1000; i++) {
        Shipment__c sh = new Shipment__c(Name='test shipment ' + i, Quantity__c=i, 
            Store__c = s.Id        
            //Printing_Press__c = [SELECT Id FROM Printing_Press__c WHERE Name = 'test press' LIMIT 1].Id);
            );
        shs.add(sh);
    }
    insert shs;
    Shipment__c sh = [SELECT Id, Shipping_Cost__c FROM Shipment__c WHERE Name = 'test shipment 999' LIMIT 1];
    Decimal estimated_cost = 48.46804666769003*2.34 + 10;
    Decimal actual_cost = sh.Shipping_Cost__c;
    System.assert(estimated_cost == actual_cost);
    Test.stopTest();


}
}