force-app/main/default/objects/Printing_Press__c/Printing_Press__c.object-meta.xml
<CustomObject>
    <label>Printing Press</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Printing Presses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Printing_Press__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the printing press</description>
    <label>Location</label>
    <scale>2</scale>
    <type>Location</type>
</CustomField>

volcano dragon/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Printing_Press__c.field-meta.xml
<CustomField>
    <fullName>Printing_Press__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Printing Press</label>
    <referenceTo>Printing_Press__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

volcano dragon/force-app/main/default/objects/Shipment__c/fields/Shipping_Cost__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Cost__c</fullName>
    <label>Shipping Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

volcano dragon/force-app/main/default/objects/Shipment__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Store to ship to.</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>2</scale>
    <type>Location</type>
</CustomField>

volcano dragon/force-app/main/default/classes/shipmentTriggerHelper.cls
public class shipmentTriggerHelper {
    public static final Decimal costToShipPerMile = 2.34;
    public static final Decimal baseCostPerShipment = 10;
    public static final Integer maxBooksPerShipment = 100; 
    //method to find nearest printing press if not listed 
    //and then calculate the cost to ship 
    //from the press to the store
    public static void calculateShipping(List<Shipment__c> theList) {
        //get the stores
        List<ID> storeIDs = new List<ID>();
        for(Shipment__c ship : theList) {
            storeIDs.add(ship.Store__c);
        }    
        Map<ID, Store__c> theStores = new Map<ID, Store__c>([SELECT Id, Location__c FROM Store__c WHERE Id in :storeIDs]);

        //do any of these orders need a printing press assigned?
        List<Shipment__c> shipsThatNeedAPress = new List<Shipment__c>();
        Boolean pullAllPresses = false;
        for(Shipment__c s : theList) {
            if(s.Printing_Press__c == null) {
                pullAllPresses = true;
                shipsThatNeedAPress.add(s);
            }
        }
        List<ID> thePressIDs;
        Map<ID, Printing_Press__c> thePresses;

        //if so, we need to pull up the list of printing presses and we will find the closest
        if(pullAllPresses) {
            thePresses = new Map<ID, Printing_Press__c>([SELECT Id, Location__c FROM Printing_Press__c]);

            //the magic of pass-by-reference at work
            for(Shipment__c ship : shipsThatNeedAPress) {
                Location fromLoc;
                Location toLoc = theStores.get(ship.Store__c).Location__c;
                //approx circumference of the earth
                Decimal howFar = 25000;
                Decimal thisFar;

                //!!!!!!!--------------subMAIN-------------------!!!!!!!!!!
                //store the nearest printing press if not set
                for(ID it: thePresses.keySet()) {
                    fromLoc = thePresses.get(it).Location__c;
                    thisFar = Location.getDistance(fromLoc, toLoc, 'mi');
                    if(thisFar < howFar) {
                        howFar = thisFar;
                        ship.Printing_Press__c = it;
                    }
                }
            }

        //if not we can just calulate the shipping costs based on the information provided
        } else {
            for(Shipment__c ship : theList) {
                thePressIDs.add(ship.Printing_Press__c);
            }
            thePresses = new Map<ID, Printing_Press__c>([SELECT Id, Location__c FROM Printing_Press__c WHERE Id IN :thePressIDs]);
        }

        //!!!!!!!------------MAIN--------------------!!!!!!!!!
        //calculate and store the shipping cost
        for(Shipment__c ship : theList) {
            Location fromLoc = thePresses.get(ship.Printing_Press__c).Location__c;
            Location toLoc = theStores.get(ship.Store__c).Location__c;
            ship.Shipping_Cost__c = baseCostPerShipment + costToShipPerMile * Location.getDistance(fromLoc, toLoc, 'mi');
        }
    }
}